export const REQUIRED_COLUMNS = [
  "ID.",
  "Soc.",
  "Docto. Imp.",
  "Numero de Recibo",
  "Cta. Ctrto.",
  "Porcion",
  "Uni.Lect",
  "Nombre de Cliente",
  "Direccion de Facturacion",
  "Urbanizacion de Facturacion",
  "Distrito de Facturacion",
  "Predio",
  "Poblacion",
  "Tlf fijo",
  "Tlf Celular",
  "Correo Electronico",
  "T.C.",
  "Coordenada X",
  "Coordenada Y",
  "Emp.Ext.",
  "T.I",
  "Gpo",
  "Avi.Prob.Ent",
  "ID oper.",
  "M.Cgo",
  "M.SMS",
  "NºSerie",
  "Txt.breve",
  "Descr.",
  "Descrip.",
];
